apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskr-app
  labels:
    app: flaskr-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flaskr-app
  template:
    metadata:
      labels:
        app: flaskr-app
    spec:
      containers:
      - name: flaskr-app
        image: shradha11/flaskapp:0.6
        #image: ashutosh04/blogapp:<IMAGE_TAG>
        ports:
        - containerPort: 5000
        env:
            - name: FLASK_ENV
              value: "development"
            - name: CUSTOM_MESSAGE
              value: "Hello from K8s!"
---

apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: flaskr-app
  ports:
    - port: 5000
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 5000
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 30007


---

#apiVersion: v1
#kind: Service
#metadata:
  #name: flask-service-b
#spec:
  #type: LoadBalancer
  #selector:
    #app: flaskr-app
  #ports:
    #- protocol: TCP
      #port: 5000         # Exposes the service on port 5000
      #targetPort: 5000   # Forwards to the container's port
