name: "dev-flaskapp"
image_tag: 0.6
port: 30007
env: <+pipeline.variables.env>
secretName: my-secret
secretMountPath: /etc/secrets
readinessProbe:
  enabled: true
  path: /
  port: 5000
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3
  successThreshold: 1


