name: "qa-flaskapp"
image_tag: 0.6
port: 30008
env: <+pipeline.variables.env>
secretName: my-secret1
secretMountPath: /etc/secrets
readinessProbe:
  enabled: true
  path: /healthz
  port: 5000
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3
  successThreshold: 1
