{{- if eq .Values.env "dev" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
type: Opaque
data:
  username: dXNlcm5hbWU=    # base64 for "username"
  password: cGFzc3dvcmQ=    # base64 for "password"
{{- end }}